### ISSUE TITLE
missing comma

### ISSUE THREAD

**Issue by franciscogmm** [arvkevi/kneed#83]
File "C:\ProgramData\Anaconda2\lib\site-packages\kneed\data_generator.py", line 11
    mu: float = 50, sigma: float = 10, N: int = 100, seed=42
      ^
SyntaxError: invalid syntax

**Comment by arvkevi** [comment]
Hi @franciscogmm was this error generated using Python 2? If so, `kneed` only supports Python versions 3.5 and higher. I was able to reproduce the error using Python 2:

```sh
❯ python
Python 2.7.17 (default, Sep  2 2020, 03:28:10)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kneed import data_generator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin/.pyenv/versions/python2-test/lib/python2.7/site-packages/kneed/__init__.py", line 1, in <module>
    from .data_generator import DataGenerator
  File "/Users/kevin/.pyenv/versions/python2-test/lib/python2.7/site-packages/kneed/data_generator.py", line 11
    mu: float = 50, sigma: float = 10, N: int = 100, seed=42
      ^
SyntaxError: invalid syntax
```
