### ISSUE TITLE
TypeError: transform_y() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by angelosalatino** [arvkevi/kneed#96]
Hi There I have installed kneed 0.7.0

```pip install kneed==0.7.0```

I run the example in the documentation:
```
from kneed import DataGenerator, KneeLocator

x, y = DataGenerator.figure2()

print([round(i, 3) for i in x])
print([round(i, 3) for i in y])

kneedle = KneeLocator(x, y, S=1.0, curve="concave", direction="increasing")

print(round(kneedle.knee, 3))

```

I get this output:
```
[0.0, 0.111, 0.222, 0.333, 0.444, 0.556, 0.667, 0.778, 0.889, 1.0]
[-5.0, 0.263, 1.897, 2.692, 3.163, 3.475, 3.696, 3.861, 3.989, 4.091]
Traceback (most recent call last):

  File "/Users/aas358/Development/Trento/july2020/pubmed-symptoms-diseases-associations/evaluation/rank_elbow_method.py", line 54, in <module>
    kneedle = KneeLocator(x, y, S=1.0, curve="concave", direction="increasing")

  File "/opt/anaconda3/envs/dev/lib/python3.7/site-packages/kneed/knee_locator.py", line 182, in __init__
    self.y_normalized, self.direction, self.curve

TypeError: transform_y() takes 3 positional arguments but 4 were given
```

My python version is 3.7.5

**Comment by angelosalatino** [comment]
Apologies. It works indeed. I just forgot to refresh the IPython console.
